### ISSUE TITLE
No module named imp_model

### ISSUE THREAD

**Issue by rirri93** [fabro66/GAST-Net-3DPoseEstimation#15]
When I try to run gen_skes.py I obtain this error:

File "gen_skes.py", line 14, in <module>
    from imp_model.gast_net import SpatioTemporalModelOptimized1f
ModuleNotFoundError: No module named 'imp_model'

How can I resolve? 
Thanks

**Comment by yerzhan7orazayev** [comment]
Dear @rirri93, it has been resolved here, please refer.

https://github.com/fabro66/GAST-Net-3DPoseEstimation/issues/12

**Comment by rirri93** [comment]
Thank you! Resolved.
Now I have another error: 
FileNotFoundError: [Errno 2] No such file or directory: '~/GAST-Net-3DPoseEstimation/output/./output/apart.npz'

**Comment by yerzhan7orazayev** [comment]
For `gen_skes.py: error: unrecognized arguments: --animation` please refer to
https://github.com/fabro66/GAST-Net-3DPoseEstimation/issues/13.

**Comment by rirri93** [comment]
Hi, thanks. 
I copied 
human_detector.py to GAST-Net-3DPoseEstimation/lib/detector and
gen_kpts.py to GAST-Net-3DPoseEstimation/pose/pose_estimation
but the problem is still there.

**Comment by rirri93** [comment]
Ok I did `git pull` and now it works fine. Thank you
